config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, skip: :registrations
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "home", to: "pages#home", as: :home
  get "denied", to: "pages#denied", as: :access_denied

  resources :clients, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :projects, only: [:index, :new]
  end
  resources :users, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :documentations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :documentations, dependent: :destroy
  has_many :rooms, through: :locations, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/documentation.rb
class Documentation < ApplicationRecord
  belongs_to :client
  has_many :sections, dependent: :destroy

  validates :name, presence: true
  validates :favorite, inclusion: { in: [true, false] }
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :client
  has_many :rooms

  validates :name, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :location

  validates :name, presence: true, uniqueness: { scope: :location_id }
end

app/models/row.rb
class Row < ApplicationRecord
  belongs_to :section
  has_many :values, dependent: :destroy

  validates :name, presence: true
  validates :type, presence: true, inclusion: { in: %w[Headline Free Dropdown Boolean] }
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :documentation
  has_many :rows, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :client

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" },
                    uniqueness: true, length: { maximum: 255 }
  validates :username, presence: true, uniqueness: true
  validates :role, presence: true, inclusion: { in: %w[admin owner doctor assistant] }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/value.rb
class Value < ApplicationRecord
  belongs_to :row

  validates :content, presence: true
  validates :favorite, presence: true, inclusion: { in: [true, false] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def authenticate_admin!
    redirect_to root_path, alert: 'Not authorized.' unless current_user.role == 'admin'
  end

  def authenticate_owner!
    redirect_to root_path, alert: 'Not authorized.' unless current_user.role == 'owner'
  end

  # before_action :configure_permitted_parameters, if: :devise_controller?

  # protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: %i[username firstname lastname role])
  #   devise_parameter_sanitizer.permit(:account_update, keys: %i[username firstname lastname role])
  # end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_admin!, except: [:show]

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to client_path(@client), notice: "Client was successfully created."
    else
      render :new, notice: "Client was not created."
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      redirect_to client_path(@client), notice: "Client was successfully updated."
    else
      render :edit, notice: "Client was not updated."
    end
  end

  def destroy
    @client = Client.find(params[:id])
    if @client.destroy
      redirect_to clients_path, notice: "Client was successfully deleted."
    else
      redirect_to clients_path, notice: "Client was not deleted."
    end
  end

  private

  def client_params
    params.require(:client).permit(:name)
  end

  def authenticate_admin!
    # Ensure only admins or admins can access
    unless current_user.role == 'admin'
      redirect_to root_path, alert: "You are not authorized to access this page."
    end
  end
end

app/controllers/documentation_controller.rb
class DocumentationController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    if current_user && current_user.role == "admin"
      # Admin-specific logic
      redirect_to clients_path
    elsif current_user && current_user.role == "owner"
      # Owner-specific logic
      redirect_to client_path(current_user.client)
    elsif current_user && current_user.role == "doctor"
      # Doctor-specific logic
      redirect_to documentation_path(current_user.client)
    elsif current_user && current_user.role == "assistant"
      # Assistant-specific logic
      redirect_to documentation_path(current_user.client)
    else
      # Default logic
      redirect_to access_denied_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!
  before_action :check_owner, only: [:new, :create]

  def new
    @user = User.new(client_id: params[:client_id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "User was successfully created."
    else
      render :new
    end
  end

  def index
    @client = Client.find(params[:client_id])
    @user = current_user
    @users = User.where(client_id: @client.id)
  end

  def edit
    @user = User.find(params[:id])
    @user.client_id = params[:client_id]
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username, :firstname, :lastname, :role, :client_id)
  end

  def check_owner
    return if (current_user && current_user.role == 'owner') || current_user.role == 'admin'

    redirect_to root_path, alert: 'Not authorized to perform this action.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/edit.html.erb
<h1>Edit Client</h1>

<%= simple_form_for @client do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>
      <ul>
        <% @client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.submit "Update Client" %>
  </div>
<% end %>

<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<div class="page-container p-3 d-flex justify-content-center">
  <div class="clients-content">
    <h1>Clients</h1>
      <%= link_to new_client_path, class: "btn btn-primary" do %>
        New Client
      <% end %>
    <div class="client-cards">
      <% @clients.each do |client| %>
        <div class="card" style="width: 18rem;">
          <%= link_to client_path(client) do %>
            <div class="card-header">
              <%= client.name %>
            </div>
          <% end %>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">ID: <%= client.id %></li>
            <li class="list-group-item">Users: <%= client.users.count %></li>
            <li class="list-group-item">Signed up: <%= client.created_at.strftime("%d-%m-%Y") %></li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= simple_form_for @client do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>
      <ul>
        <% @client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.submit "Create Client" %>
  </div>
<% end %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<div class="page-container p-3 d-flex justify-content-center">
  <div class="clients-content">
    <h1><%= @client.name %></h1>
<!-- button to add users to the client -->
    <%= link_to 'New User', new_user_path(client_id: @client.id), class: 'btn btn-primary' %>
<!-- button to edit the client -->
    <%= link_to edit_client_path(@client), class: "btn btn-primary" do %>
      Edit Client
    <% end %>
<!-- button to delete the client -->
    <%= link_to @client, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
      Delete Client
    <% end %>
<!-- button to go back to the clients index -->
    <%= link_to 'Back', clients_path, class: "btn btn-primary" %>
  </div>
<!-- card with the client's information -->
  <div class="card" style="width: 18rem;">
    <div class="card-header">
      <%= @client.name %>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">ID: <%= @client.id %></li>
      <%= link_to users_path(client_id: @client.id) do %>
        <li class="list-group-item">Users: <%= @client.users.count %></li>
      <% end %>
      <li class="list-group-item">Signed up: <%= @client.created_at.strftime("%d-%m-%Y") %></li>
      <li class="list-group-item">Last Edited: <%= @client.updated_at.strftime("%d-%m-%Y") %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Docudoc</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="page-container">
  <h1>Home</h1>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.input :password, hint: 'Leave blank if you do not want to change the password.' %>
    <%= f.input :password_confirmation, hint: 'Leave blank if you do not want to change the password.' %>
    <%= f.input :username %>
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    <%= f.input :role, collection: [['Owner', 'owner'], ['Assistant', 'assistant']], include_blank: false %>

    <%= f.input :client_id, as: :hidden, input_html: { value: @user.client_id } %>
    <div class="readonly-client">
      Client: <strong><%= Client.find(@user.client_id).name %></strong>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Update User" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<%= link_to 'New User', new_user_path(client_id: @client.id), class: 'btn btn-primary' %>
<%= link_to 'Back', client_path(@client), class: 'btn btn-primary' %>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Username</th>
      <th>Role</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.role %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user, client_id: @client.id) %>
          <%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.input :username %>
    <%= f.input :firstname %>
    <%= f.input :lastname %>

    <%= f.input :role, collection: [['Owner', 'owner'], ['Doctor', 'doctor'], ['Assistant', 'assistant']], include_blank: false %>

    <%= f.input :client_id, as: :hidden, input_html: { value: @user.client_id } %>
    <%= f.input :client, as: :string, input_html: { value: Client.find(@user.client_id).name, readonly: true } do %>
      <span> <%= Client.find(@user.client_id).name %></span>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.submit "Create User" %>
  </div>
<% end %>